### ISSUE TITLE
rev_A

### ISSUE THREAD

**Issue by JasonLin43212** [ibelkebeer/cerealKillers#1]
It is clear how a user would interact with the data. It is pretty interesting because it is relevant to our lives and current time and political atmosphere. Your maps and timeline does encourage me to explore the information. However, one deadly pitfall is "How would you make the weird shapes of the states hoverable or interactiveable?"

**Comment by rachel-ng** [comment]
We'll be using `d3.on("mouseover", function)` and `d3.mouse(container)` to make the states in the map interactive. Here's a better [example](https://vida.io/documents/4vZ9mRGyepoyQxFcK) of something similar (in execution) to what we're aiming for. 

We've also added it to the [Responsiveness and User Interaction](https://github.com/ibelkebeer/cerealKillers#responsiveness-and-user-interaction) section of our README.md, thank you for pointing this out.
