### ISSUE TITLE
rev_C

### ISSUE THREAD

**Issue by tinawong15** [ibelkebeer/cerealKillers#2]
Your chosen display format for your chosen data seems appropriate because the United States map allows the user to clearly see how different states compare in terms of gun violence deaths/injuries. However, in your Questions Explored section, your team mentions seeing how many people survive gun violence. An additional display format you may want to include is dividing the amount of deaths and amount of injuries for each state to see how the breakdown compares between all the states. A visualization of this would allow the user to clearly see this.

**Comment by rachel-ng** [comment]
We'll be presenting users with information on how many injuries and deaths were caused when they [hover over the states](https://github.com/ibelkebeer/cerealKillers#responsiveness-and-user-interaction). 

We'll also be allowing users to use buttons or a dropdown menu to choose what kind of data they want to see.
