### ISSUE TITLE
rev_D

### ISSUE THREAD

**Issue by qzhou0** [ibelkebeer/cerealKillers#3]
Since your data set has "incident characteristics", perhaps you can try to get that information and allow the user to filter what type of incident was it (or perhaps color code?)-- shooting, murder, suicide?

**Comment by rachel-ng** [comment]
The incident characteristics aren't that specific, they only specify whether the people shot are wounded and/or dead depending on how many victims there are, whether or not it's a mass shooting (4 people or more), and not much else. 

More specifically, for each characteristic, there aren't specific qualifiers for each situation, so the 3 major characteristics I've observed all look like this: 

`Shot - Dead (murder, accidental, suicide)`
`Shot - Wounded/Injured`
`Mass Shooting (4+ victims injured or killed excluding the subject/suspect/perpetrator, one location)`
