### ISSUE TITLE
rev_C

### ISSUE THREAD

**Issue by qzhou0** [ibelkebeer/cerealKillers#4]
You can also try to incoroprate the exact location or the city, if possible and time allows, since you have rather specific information in your database. [This gallery gives information for airports](https://observablehq.com/@mbostock/u-s-airports-voronoi).

**Comment by rachel-ng** [comment]
I don't think this would be possible as we'll be combining the data by month and not including the specific location of each incident, and because there are 240k incidents in the dataset.
