### ISSUE TITLE
rev_B

### ISSUE THREAD

**Issue by ecrystale** [ibelkebeer/cerealKillers#5]
The aim of your project seems to be to create an interactive map to provide users with information on gun violence by the state and the statistics involved in that. However, there are some parts that are a bit unclear. If the hover only works for state information, how does one determine whether an area rather than state is safe or not? Would a user be able to choose an area if they only know the name, but not the location (this is more of an extra)? How are survivors counted - injured survivors or everyone that was present?

**Comment by rachel-ng** [comment]
The survivors are counted by whether or not they were shot — so only people who were injured and survived are counted.

**Comment by rachel-ng** [comment]
We've generalized our data in order to reduce the size of our dataset, so we'll only be including states per month as a whole. As a result, the users will be unable to determine whether specific areas are safe or not.
