### ISSUE TITLE
rev_D

### ISSUE THREAD

**Issue by JasonLin43212** [ibelkebeer/cerealKillers#6]
One way to encourage deeper exploration and understanding of the data can be adding a feature where you switch between looking at the statistics for each state to looking at the statistics for each city. This many offer a more detailed look at where these tragedies occur most often in a state. Then you can do some analysis on that data, such as which city in a particular state has the highest / lowest crime rate.

**Comment by MaiRachlevsky** [comment]
Thank you for your feedback. We've generalized our data in order to reduce the size of our dataset, so we'll only be including states per month as a whole.
