### ISSUE TITLE
rev_A

### ISSUE THREAD

**Issue by jerry1ye10** [ibelkebeer/cerealKillers#7]
It's definitely clear how a user could interact with the data, and I think it does a good job of being easy and clear to use for users. I'm a bit unsure of what exactly the time lapse graph is. Will the user be able to choose the year of data?

**Comment by rachel-ng** [comment]
The time lapse graph will go through all of the data for all states, month by month.  
Users will be able to click on the timeline to see specific points in time of their choosing.
